networks:
  realtime:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks: [realtime]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  backend:
    build: ./server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks: [realtime]

  speed_publisher:
    build:
      context: ./provider
      dockerfile: Dockerfile
    networks: [realtime]

  ros_to_redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks: [realtime]

  frontend:
    build: ./frontend/realtime-dashboard
    depends_on:
      - backend
    ports:
      - "3000:80"          
    networks: [realtime]
